runtime: python39  # specify the python version
instance_class: F2  # choose an instance class based on your needs
automatic_scaling:
  target_cpu_utilization: 0.65  # set the auto-scaling configurations
  min_instances: 1
  max_instances: 2

network: 
  session_affinity: true  # for socketio session affinity

entrypoint: gunicorn -b :$PORT main:app  # replace "your_app_name" with the name of your flask app

# specify any other configurations based on your app's needs
