runtime: python39 # Specify the Python version
instance_class: F2 # Choose the instance class, F2 is a common choice for lightweight applications.
automatic_scaling: 
  target_cpu_utilization: 0.65 # This scales the instances based on CPU utilization.
  min_instances: 1
  max_instances: 1

entrypoint: python main.py # Your entry point, typically where your server is initialized.

# You can set environment variables here, if needed.
env_variables:
  SECRET_KEY: 'your-secret-key'

# If you have static files like CSS, JS, or images:
handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app
